### ISSUE TITLE
How to save mpl image to file

### ISSUE THREAD

**Issue by camillerievan** [Qulacs-Osaka/qulacs-visualizer#108]
Hi,

Nice library.  Is there a way to save the mpl image to a file, rather than display it on screen?

Thanks

Evan

**Comment by Hiroya-W** [comment]
Hi @camillerievan 

If you are running from the command line (not on Jupyter Notebook), you can use the following program.

```py
from qulacs import QuantumCircuit
import matplotlib.pyplot as plt
from qulacsvis.visualization import MPLCircuitlDrawer # Use instead of circuit_drawer

# Build a your quantum circuit
circuit = QuantumCircuit(3)
circuit.add_X_gate(0)
circuit.add_Y_gate(1)
circuit.add_Z_gate(2)
circuit.add_dense_matrix_gate(
    [0, 1], [[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 0, 1], [0, 0, 1, 0]]
)
circuit.add_CNOT_gate(2, 0)
circuit.add_X_gate(2)

drawer = MPLCircuitlDrawer(circuit)
fig = drawer.draw()
plt.savefig("output.png") # save to file
```

However, in many cases you will want to run it on Jupyter Notebook. This is apparently broken. Sorry. I am working on fixing this.

**Comment by camillerievan** [comment]
Thanks - works great!

**Comment by Hiroya-W** [comment]
- #110 

Fixed. Upgrade qulacsvis to v0.7.0 and use it this way.

```py
circuit_drawer(circuit, "mpl", filename="output.png")
```
