### ISSUE TITLE
Implementing weights of a Hamiltonian in Qulacs.

### ISSUE THREAD

**Issue by camillerievan** [Qulacs-Osaka/qulacs-visualizer#115]
- it was a bug from my side - please delete this post

**Comment by Hiroya-W** [comment]
Hi @camillerievan 
I'm glad you found the cause of this problem. Good luck. I will close this Issue.

If you need support, you can use the [Qulacs Slack community](https://docs.qulacs.org/en/latest/#qulacs-documentation) or [Issues in the Qulacs repository](https://github.com/qulacs/qulacs/issues).
