### ISSUE TITLE
Matplotlibを使った描画で、DenseMatrixGateが重なって表示されるケースがある

### ISSUE THREAD

**Issue by Hiroya-W** [Qulacs-Osaka/qulacs-visualizer#54]
```py
def dense_matrix_gate_with_multiple_target_bits_should_not_overlap() -> QuantumCircuit:
    circuit = QuantumCircuit(5)
    mat = np.identity(2 ** 3)
    # 3-qubit gate applied to [0,2,4]
    circuit.add_dense_matrix_gate([0, 2, 4], mat)
    # 2-qubit gate applied to [1,3]
    mat = np.identity(2 ** 2)
    circuit.add_dense_matrix_gate([1, 3], mat)
    return circuit
```

のような回路を作成した場合、テキストベースの描画で得られる結果のように、重ならずに描画される必要があります。
```
   ___           
  |DeM|          
--|   |----------
  |_ _|          
   | |     ___   
   | |    |DeM|  
---| |----|   |--
   | |    |_ _|  
  _| |_    | |   
  |   |    | |   
--|   |----| |---
  |_ _|    | |   
   | |    _| |_  
   | |    |   |  
---| |----|   |--
   | |    |___|  
  _| |_          
  |   |          
--|   |----------
  |___|          

```

現状、Matplotlibの描画では重なって表示されてしまっています。
![output](https://user-images.githubusercontent.com/43127622/147325203-b2f6e343-ba01-4980-857a-9732bab5001b.png)

**Comment by kawamochi** [comment]
原因理解した
現状Target Indexだけみて判定しているけど間も見る必要があるんね
Target IndexのMinからMaxまで見たら解決しそう

Controll Indexに関しては、Control Indexが存在する場合Layerを切り分けるように対応しているんやけど
これも合わせて変更して「Target IndexとControl IndexのMinからMaxまで走査してConflict判定をする」ように変更した方が良さそう？

**Comment by Hiroya-W** [comment]
>「Target IndexとControl IndexのMinからMaxまで走査してConflict判定をする」ように変更した方が良さそう？

その方がレイヤが分かれず、空いている部分に詰めて表示することが出来るようになるのなら、その方がいいな、という感じがするね
