### ISSUE TITLE
余分なスペースの削除

### ISSUE THREAD

**Issue by kawamochi** [Qulacs-Osaka/qulacs-visualizer#69]
https://github.com/Qulacs-Osaka/scikit-qulacs/blob/152-reservoir/skqulacs/qrc/reservoir.ipynb

これの表示を直す

**Comment by kawamochi** [comment]
衝突が起きた時点でレイヤを切ってしまっているのが問題、各量子ビット毎にキューのようなもので管理したら楽か？
複数量子ビットの回路の扱いに注意が必要

**Comment by Hiroya-W** [comment]
@kawamochi 大きな改修になる部分だと思うので時間はかかりそうだと思っていますが、今どんな感じでしょう？詰まってることとか無さそうですか？

**Comment by Hiroya-W** [comment]
@kawamochi 進捗どうでしょう？PRのDraftなど、コードを載せてくれれば相談にのるので、また教えてください！
